export const APP_SET_ERROR = 'USER/SET_ERROR';
export const APP_SET_STATUS = 'USER/SET_STATUS';
export const APP_SET_INITIALIZE = 'USER/SET_INITIALIZE'

export const GET_ALL_USERS_REQEST = 'SAGA/GET_ALL_USERS_REQEST'

export const GET_ALL_USERS = 'GET_ALL_USERS';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const REMOVE_USER = 'REMOVE_USER';

