export const APP_SET_ERROR = 'APP/SET_ERROR';
export const APP_SET_STATUS = 'APP/SET_STATUS';
export const APP_SET_INITIALIZE = 'APP/SET_INITIALIZE'

export const GET_ALL_USERS_REQEST = 'SAGA/GET_ALL_USERS_REQEST'
export const ADD_NEW_USER_REQEST = 'SAGA/ADD_NEW_USERS_REQEST'

export const GET_ALL_USERS = 'USER/GET_ALL_USERS';
export const ADD_NEW_USER = 'USER/ADD_NEW_USER';
export const UPDATE_USER = 'USER/UPDATE_USER';
export const REMOVE_USER = 'USER/REMOVE_USER';
export const FETCH_NEW_USER = 'USER/FETCH_NEW_USER'

